version: '3'

tasks:
  run:
    cmds:
      - go run cmd/encard/encard.go

  lint:
    cmds:
      - golangci-lint run

  test:
    cmds:
      # - go test -v ./...
      - set -o pipefail && go test -v ./... -json | tparse -all

  build:
    cmds:
      - go build cmd/encard/encard.go