name: test
run-name: ${{ github.actor }} test
on: [push]
jobs: 
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v2
        with:
          node-version: '20'
      - run: npm install -g bats
      - run: bats -v